# Generated by Django 2.0.5 on 2018-06-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRescord',
            new_name='AccessRecord',
        ),
    ]
